Proyecto/Proyecto/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import static
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('parches.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name='view/VistasPCU/custom_reset_password_form.html',
        email_template_name='view/VistasPCU/custom_reset_password_email.html',
        success_url='/reset_password_send/'), name='password_reset'),

    path('reset_password_send/', auth_views.PasswordResetDoneView.as_view(
        template_name='view/VistasPCU/custom_reset_password_done.html'), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='view/VistasPCU/custom_reset_password_confirm.html',
        success_url='/reset_password_complete/'), name='password_reset_confirm'),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='view/VistasPCU/custom_reset_password_complete.html'), name='password_reset_complete'),
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

Proyecto/parches/urls.py
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.urls import include, path

from . import views
from .views import (ActividadDetailAPIView, ActividadListAPIView,
                    EmpresaPersonaDetailAPIView, EmpresaPersonaListAPIView,
                    PuntoDeportivoDetailView, get_sorted_puntos_deportivos)

urlpatterns = [
    
    path('', views.HomepageProject, name='vistaPrincipal', ),
    path('Register/User', views.registerUser, name='register'),
    path('login', views.login, name='login'),
    path('CreateEvent', views.CreateEvent, name='CreateEvent'),
    path('Register/Company', views.RegisterCompany, name='RegisterCompany'),
    path('profile', views.Profile, name='profile'),
    path('coverImage', views.CoverImage, name='CoverImagen'),
    path('Report/<int:pk>/', views.ReportEvent, name='Report'),
    path('select/user', views.SelectUser, name='selectUser'),
    path('eventCreate',views.eventForUser, name='eventUser' ),
    path('eliminar/<int:idactividad>', views.viewEventoELI, name='eliminar'),
    path('Update/<int:idactividad>', views.UpdateEvent, name='update'),
    path('updateUser/<int:idregistro>/<str:tipousuario>', views.UpdateUser, name='UpdateUser'),
    path('updateUserCompany/<int:idregistro>/<str:tipousuario>', views.UpdateUserCompany, name='UpdateUserCompany'),
    path('eventos', views.MostrarEvento, name='mostrarEventos'),
    path('eliminar/<int:idactividad>', views.viewEventoELI, name='eliminar'),
    
    path('detalles/<int:idactividad>/', views.DetallesEvento, name='detalles_evento'),
    path('profile/dislikes/<int:pk>', views.adddislike, name='dislike'),
    path('profile/likes/<int:pk>', views.addLikes, name='likes'),
    path('interfaz/<str:empresa_idempresa>/User', views.interfazUser, name='interfaz'),
    path('profile/dislikes/<int:id>/comment', views.addCommentDislike, name='dislikecomment'),
    path('profile/likes/<int:id>/comment', views.addCommentLikes, name='likescomment'),
    path('profile/delete/<int:id>/comment', views.deleteComment, name='deleteComment'),
    path('reportar_usuario/<int:pk>/', views.send_report_email, name='report'),
    
    path('detalles/<int:idactividad>/', views.DetallesEvento, name='detalles_evento'),
    path('profile/delete/<int:id>/comment/user', views.deleteCommentUser, name='deleteCommentUser'),
    path('join/event/<int:pk>', views.joinEvent, name='joinEvent'),
    path('evento/inscripcion/', views.eventoRegistration,name='inscripcion'),
    path('evento/inscripcion/anular/<int:idactividad>', views.deleteRegistration , name='inscripcionDeletes'),
    path('reportar_usuario/<int:pk>/', views.send_report_email, name='report'),
    path('Report/<int:pk>/', views.ReportEvent, name='Report'),
    path('participantes/evento/<int:pk>/', views.eventParticipante, name='participantes'),
    path('eliminar/participantes/evento/<int:idregistro>/<int:pk>', views.anularinscripcion, name='Eliminarparticipantes'),
    path('resena/Evento/<int:idEvento>',views.calificacionFinal, name='finalReseña' ),
     

    path('puntoDeportivo', views.agregarPd, name='puntoDeportivo'),
    # path('mostrarPd/', views.mostrarPd, name='mostrarPd'),
    path('punto_deportivo/<int:pk>/', PuntoDeportivoDetailView.as_view(), name='punto_deportivo_detail'),
    path('api/get_sorted_puntos_deportivos/', get_sorted_puntos_deportivos, name='get_sorted_puntos_deportivos'),
    
    path('api/actividades/', ActividadListAPIView.as_view(), name='actividad-list'),
    path('api/actividades/<int:pk>/', ActividadDetailAPIView.as_view(), name='actividad-detail'),
    path('api/usuarios/', EmpresaPersonaListAPIView.as_view(), name='usuario-list'),
    path('api/usuarios/<int:pk>/', EmpresaPersonaDetailAPIView.as_view(), name='usuario-detail'),
    
]

Proyecto/parches/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
# from django.contrib.auth.models import User


import uuid

from django.conf import settings
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin, User)
from django.db import models
from django.utils import timezone


class Actividad(models.Model):
    Futbol = "FUTBOL"
    Baloncesto = "Baloncesto"
    juegoMesa = "Juego de mesa"
    Voleibol = "Voleibol"
    pasarElRato = "Pasar el rato"
    natacion = "natacion"
    patinaje = 'patinaje'
    tenis= 'tenis'
    cilcismo = 'ciclismo' 
   
    deporte = [
        (Futbol, 'Futbol'),
        (Baloncesto, 'Baloncesto'),
        (juegoMesa, 'Juegos De Mesa'),
        (Voleibol,'Voleibol'),
        (pasarElRato,'Pasar el rato'),
        (natacion, 'Natacion'),
        (patinaje, 'Patinaje'),
        (tenis, 'Tenis'),
        (cilcismo,'Cilcismo')
    ]
 
    idactividad = models.AutoField(db_column='idActividad', primary_key=True)
    nombreactividad = models.CharField(db_column='nombreActividad', max_length=30)
    tipoactividad = models.CharField(db_column='tipoActividad', choices=deporte,max_length=15)
    lugar = models.CharField(max_length=40, null=True, blank=True)
    # ubicacion = models.CharField(max_length=80)
    fechainicio = models.CharField(db_column='fechaInicio', max_length=40)
    fechafin = models.CharField(db_column='fechaFin', max_length=40)
    descripcion = models.TextField(db_column="descripcion", max_length=75, blank=True, null=True)
    hora = models.CharField(max_length=40)
    imagen = models.ImageField(upload_to='actividad/', max_length=80)
    contacto = models.CharField(max_length=30)
    estado = models.CharField(max_length=20)
    puntosdeportivos = models.ForeignKey('Puntosdeportivos', models.DO_NOTHING, null=True, blank=True)
    empresa_idempresa = models.ForeignKey('EmpresaPersona', on_delete=models.CASCADE, db_column='empresa_idEmpresa', null=True)

    latitud = models.FloatField(blank=True, null=True)
    longitud = models.FloatField(blank=True, null=True)

    class Meta:
        db_table = 'actividad'
        unique_together = (('idactividad', 'puntosdeportivos', 'empresa_idempresa'),)

    
    def delete(self, using= None, keep_parents=False):
        self.imagen.storage.delete(self.imagen.name)
        super().delete()



class Documento(models.Model):
    iddocumento = models.AutoField(db_column='idDocumento', primary_key=True)  # Field name made lowercase.
    documentocol = models.FileField(db_column='Documentocol', upload_to='documentos/', max_length=100)  # Field name made lowercase.
    empresa_idempresa = models.ForeignKey('EmpresaPersona', db_column='empresa_idEmpresa', on_delete=models.CASCADE) # Field name made lowercase.

    class Meta:
        db_table = 'documento'
    
    def delete(self, using: None , keep_parents= False):
        self.documentocol.storage.delete(self.documentocol.name)
        super().delete()
    




class EmpresaPersonaManager(BaseUserManager):
    def create_user(self, usuario, correo, telefono, password):
        usuario = self.model(usuario=usuario, correo=correo, telefono=telefono)
        usuario.usuario_activo = True
        usuario.set_password(password)  
        usuario.save()
        return usuario

    def create_superuser(self, usuario, password):
        usuario = self.create_user(usuario=usuario, correo="", telefono=0, password=password)
        usuario.usuario_administrador = True
        usuario.save()
        return usuario



class EmpresaPersona(AbstractBaseUser, PermissionsMixin):
    TipoUser = [
        ('E', 'E'),
        ('U', 'U')
    ]

    Estado_ENUM = [
        ('A', 'A'),
        ('I', 'I')
    ]

    idregistro = models.AutoField(db_column='idRegistro', primary_key=True)  # Field name made lowercase.
    nit = models.CharField(max_length=45, blank=True, null=True)
    usuario = models.CharField(max_length=40, db_column='usuario', unique=True)
    password = models.CharField(max_length=128)
    nombreempresa = models.CharField(db_column='nombreEmpresa', unique=True, max_length=40, null=True)  # Field name made lowercase.
    direccion = models.CharField(max_length=40)
    correo = models.CharField(max_length=45)
    telefono = models.CharField(max_length=40)
    tipousuario = models.CharField(db_column='tipoUsuario', choices=TipoUser, max_length=1)  # Field name made lowercase.
    fotoperfil = models.ImageField(upload_to='fotoperfil/', max_length=80, null=True)
    resena = models.CharField(max_length=40)
    usuario_activo = models.BooleanField(default=True)
    usuario_administrador = models.BooleanField(default=False)
    estado = models.CharField(choices=Estado_ENUM, default='I', max_length=1)
    is_active = models.BooleanField(default=True)
    likes = models.ManyToManyField('self', blank=True, related_name='likes')
    dislikes = models.ManyToManyField('self', blank=True, related_name='dislikes')
    Descripcion = models.TextField(max_length=180, blank=True, null=True)

    

     
    REQUIRED_FIELDS = ['correo', 'telefono'] 
    USERNAME_FIELD = 'usuario'
    EMAIL_FIELD = 'correo'
    # PASSWORD_FIELD = 'contrasena'  

    objects = EmpresaPersonaManager()

    def __str__(self):
        return self.usuario

    def has_perm(self,perm, obj = None):
        return True

    def has_module_perms(self, app_label):
        return True
     
    class Meta:
         db_table = 'empresa/usuario'

    @property
    def is_staff(self):
        return self.usuario_administrador



    # class Meta:
    #     managed = Fals
    #     db_table = 'empresa/persona'

class comentarioUSer(models.Model):
    comment = models.TextField(db_column='comentario')
    created_on = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(EmpresaPersona, on_delete=models.CASCADE, related_name='comment_author')
    receptor = models.ForeignKey(EmpresaPersona, on_delete=models.CASCADE, db_column='usuario')
    likes = models.ManyToManyField(EmpresaPersona, blank=True, related_name='comment_likes')
    dislikes = models.ManyToManyField(EmpresaPersona, blank=True, related_name='comment_dislikes')
    
    # parent = models.ForeignKey("self", on_delete=models.CASCADE, blank=True, null=True, related_name='+')

    # @property
    # def children(self):
    #     return comentarioUSer.objects.filter(parent=self).order_by('created_on').all()
    
    # @property
    # def is_parent(self):
    #     if self.parent is None:
    #         return True
    #     return False
    





class Persona(models.Model ):
    idpersona = models.AutoField(db_column='idPersona', primary_key=True)
    documento = models.CharField(max_length=45)
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=45)
    correo = models.CharField(max_length=45)
    telefono = models.CharField(max_length=40)
    empresa_idEmpresa = models.ForeignKey('EmpresaPersona', db_column='empresa_idEmpresa', on_delete=models.CASCADE)
    

    class Meta:
        
        db_table = 'persona'
        


class Puntosdeportivos(models.Model):
    idPuntoDeportivo = models.AutoField(db_column='idPuntoDeportivo', primary_key=True)
    nombre = models.CharField(db_column='nombre',max_length=50)
    direccion = models.CharField(db_column='direccion', max_length=40)

    class Meta:
   
        db_table = 'puntosdeportivos'


class Realizacion(models.Model):
    actividad_idactividad = models.ForeignKey('Actividad',on_delete=models.CASCADE,db_column='actividad_idActividad') 
    usuario_idusuario = models.ForeignKey('EmpresaPersona',on_delete=models.CASCADE, db_column='usuario_idEmpresaPersona')  
    comentarios = models.CharField(max_length=45, null=True)
  

    class Meta:
        
        db_table = 'realizacion'

Proyecto/parches/templates/view/VistasPCU/PantallaDeCarga.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static "CSS/bootstrap(1).css" %}" />
    <link rel="stylesheet" href="{% static "CSS/pantallaCarga.css" %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" />
</head>

<body>
    <style>
        .background-container {
            background-image: url(/static/IMG/Fondo\ degradado\ de\ tonos\ verdes\ _\ Vector\ Premium.png);
        }
    </style>
    <div class="background-container">
        <div class="container-fluid">
            <img src="{% static "IMG/WhatsApp_Image_2023-04-30_at_9.22.07_PM-removebg-preview.png" %}" alt="" class="img">
        </div>
        <div class="row">
            <div class="col-12 text-center">
                <div class="loading-icon">
                    <img src="{% static "IMG/4843010_ball_beach_game_sport_volleyball_icon.png" %}" alt="">
                </div>
                <div class="loading-icon">
                    <img src="{% static "IMG/8541666_basketball_ball_icon.png" %}" alt="">
                </div>
                <div class="loading-icon">
                    <img src="{% static "IMG/9023871_tennis_ball_fill_icon.png" %}" alt="">
                </div>
                <div class="loading-icon">
                    <img src="{% static "IMG/9023883_soccer_ball_fill_icon.png" %}" alt="">
                </div>
            </div>
        </div>
    </div>
</body>

</html>

Proyecto/parches/templates/view/VistasPCU/UpdateUser.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static "CSS/bootstrap(1).css" %}">
    <link rel="stylesheet" href="{% static "CSS/registro.css" %}">  
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
        integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
        integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" />
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
</head>
<body style=" background-image: url(https://cdn.leonardo.ai/users/0a8c9781-41d8-4096-9b34-bfb6a595afce/generations/17773aab-41f9-451f-a98e-c9bd2be457ad/Leonardo_Diffusion_XL_un_fondo_bonito_y_llamativo_para_un_logi_0.jpg) ; background-repeat: no-repeat; background-size: cover;">

{% if user.is_authenticated %}
<div class="container-fluid d-flex justify-content-center align-items-center " style="height: 50.8rem;">
    <div class="row cartaR mt-5" style="background-color: rgba(255, 255, 255, 0.445);">
        <div class="text-center palabraRegistro">
            <h2 class="text-white" style="font-style: italic;">Actualiza tu informacion</h2>
            <hr class="border border-4 border border-black">
        </div>
        <form method="post" enctype="multipart/form-data" >
            {% csrf_token %}
            <div class="inputRegistro">
                <div class="nombreRegistro d-block">
                    {{ form.usuario }}
                </div>
                <div class="correoRegistro d-block">
                    {{ form.correo }}
                </div>
                <div class="telefonoRegistro">
                    {{ form.telefono }}
                </div>
                <div class="contraseñaRegistro">
                    {% if form.nombreempresa.value %}
                    {{ form.nombreempresa }}
                    {% endif %}
                    {% if form.direccion.value %}
                    {{ form.direccion }}
                    {% endif %}
                </div>
                <div> {{ form.fotoperfil }} </div>
                <div class="mb-1">
                    <h3 style="font-style:italic ;">actualiza tu descripcion</h3>
                    {{ form.Descripcion }}
                </div>
            </div>
            <div class="botonRegistrarse mb-4">
                <button type="submit" class="btn btn-primary w-50 mt-3">Guardar cambios</button>
            </div>
        </form>
    </div>
</div>

{% endif %}
</body>

</html>

Proyecto/parches/templates/view/VistasPCU/custom_reset_password_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Restablecimiento de contraseña completado</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
    crossorigin="anonymous"></script>
    <style>
        body {
            background-color: #f8f9fa;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        .container {
            background-color: #fff;
            text-align: center;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.3);
        }

        h1 {
            font-size: 24px;
            color: #333;
        }

        p {
            font-size: 18px;
            color: #666;
        }

        a {
            text-decoration: none;
            color: #007BFF;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Restablecimiento de contraseña completado</h1>
        <p>Tu contraseña se ha restablecido con éxito. Ahora puedes iniciar sesión con tu nueva contraseña.</p>
        <a href="{% url 'login' %}">Volver al inicio de sesión</a>
    </div>
</body>
</html>

Proyecto/parches/templates/view/VistasPCU/custom_reset_password_done.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Recuperación de contraseña solicitada</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
    <style>
        body {
            background-color: #f8f9fa;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        .container {
            background-color: #fff;
            text-align: center;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.3);
        }

        h1 {
            font-size: 24px;
            color: #333;
        }

        p {
            font-size: 18px;
            color: #666;
        }
    </style>
</head>

<body>
    <div class="container">
        <h1>Recuperación de contraseña solicitada</h1>
        <p>Se ha enviado un correo electrónico con las instrucciones para restablecer tu contraseña. Revisa tu bandeja
            de entrada.</p>
    </div>
</body>

</html>

Proyecto/parches/templates/view/VistasPCU/custom_reset_password_email.html
{% block subject %}
    Recuperación de contraseña
{% endblock %}

{% block text %}

{{ user.get_username }}, Has solicitado un restablecimiento de contraseña para tu cuenta. Para continuar con el proceso, haz clic en el enlace a continuación:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

Si no solicitaste esta recuperación, ignora este mensaje.

{% endblock %}

Proyecto/parches/templates/view/VistasPCU/custom_reset_password_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Recuperación de contraseña</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div style="display: block; align-content: center; justify-content: center; text-align: center; margin-top: 250px;">
                <h1>Solicitar restablecimiento de contraseña</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Enviar solicitud</button>
                </form>
            </div>
        </div>
    </div>
</body>

</html>

Proyecto/parches/templates/view/VistasPCU/eventos_en_punto_deportivo.html
<!-- En tu archivo eventos_en_punto_deportivo.html -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eventos en Punto Deportivo</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
        crossorigin="anonymous">
</head>

<body>

    <div class="container">
        <h1>Eventos en {{ punto_deportivo.nombre }} - {{ punto_deportivo.direccion }}</h1>
    
        {% for actividad in actividades_relacionadas %}
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ actividad.nombreactividad }}</h5>
                    <!-- Otros detalles de la actividad ... -->
                </div>
            </div>
        {% endfor %}
    
    </div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>

</body>

</html>

Proyecto/parches/templates/view/VistasPCU/punto_deportivo_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</head>

<body>
    <div class="container-fluid">
        <div class="row justify-content-center align-items-center">
            <div class="col-12 text-center mb-4">
                <h1>Eventos realizados en {{ punto_deportivo.nombre }} - {{ punto_deportivo.direccion }}</h1>
            </div>

            {% for evento in punto_deportivo.actividad_set.all %}
            <div class="col-md-3 mb-3">
                <div class="card" style="width: 18rem;">
                    <img src="{{ evento.imagen.url }}" class="card-img-top" alt="..." style="height: 120px;">
                    <div class="card-body">
                        <h5 class="card-title">{{ evento.nombreactividad }}</h5>
                        <p class="card-text">Fecha de inicio: {{ evento.fechainicio }}</p>
                        <p class="card-text">Hora de inicio: {{ evento.hora }}</p>
                        <p class="card-text">Descripción: {{ evento.descripcion }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</body>

</html>